version: '3.8'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: payments
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5432:5432'
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: .
    environment:
      DATABASE_URL: postgres://postgres:postgres@db:5432/payments
      PORT: 3000
    ports:
      - '3000:3000'
    depends_on:
      - db

volumes:
  db-data:
